name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
    - name: Checkout current branch
      uses: actions/checkout@v3.0.0
    - name: Setup Java
      uses: actions/setup-java@v2.5.0
      with:
        distribution: temurin
        java-version: 17
        check-latest: true
    - name: Compile scala code
      uses: coursier/cache-action@v6
    - name: Lint code
      run: ./sbt compile