name: CI

env:
  JDK_JAVA_OPTIONS: -XX:+PrintCommandLineFlags -Xmx3G # JDK_JAVA_OPTIONS is _the_ env. variable to use for modern Java
  JVM_OPTS: -XX:+PrintCommandLineFlags -Xmx3G # for Java 8 only (sadly, it is not modern enough for JDK_JAVA_OPTIONS)
  
on:
  pull_request:
    branches:
      - main
jobs:
  compile:
    runs-on: ubuntu-20.04
    timeout-minutes: 7
    steps:
    - name: Checkout current branch
      uses: actions/checkout@v3.0.0
    - name: Setup Java
      uses: actions/setup-java@v2.5.0
      with:
        distribution: temurin
        java-version: 17
        check-latest: true
    - name: Cache scala dependencies
      uses: coursier/cache-action@v6
    - name: compile code
      run: ./sbt compile